; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1nopsram]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 4MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_unflags =
    -std=gnu++11
build_flags =
    -DBOARD_HAS_PSRAM=0
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=4
    -O3
    -std=gnu++17

lib_deps =
    fastled/FastLED@^3.10.3
    olikraus/U8g2@^2.36.18
    fortyseveneffects/MIDI Library@^5.0.2
